export const HISTORY = {
    GET_HISTORY: 'GET_HISTORY',
    GET_HISTORY_PENDING: 'GET_HISTORY_PENDING',
    GET_HISTORY_FULFILLED: 'GET_HISTORY_FULFILLED',
    GET_HISTORY_REJECTED: 'GET_HISTORY_REJECTED',
}

