export const HISTORY = {
    GET_HISTORY: 'GET_HISTORY',
    GET_HISTORY_PENDING: 'GET_HISTORY_PENDING',
    GET_HISTORY_FULFILLED: 'GET_HISTORY_FULFILLED',
    GET_HISTORY_REJECTED: 'GET_HISTORY_REJECTED',

    ADD_HISTORY_ITEM: 'ADD_HISTORY_ITEM',
    ADD_HISTORY_ITEM_PENDING: 'ADD_HISTORY_ITEM_PENDING',
    ADD_HISTORY_ITEM_FULFILLED: 'ADD_HISTORY_ITEM_FULFILLED',
    ADD_HISTORY_ITEM_REJECTED: 'ADD_HISTORY_ITEM_REJECTED',

}

