export const ORGANIZATION = {
    GET_ORGANIZATION: 'GET_ORGANIZATION',
    GET_ORGANIZATION_PENDING: 'GET_ORGANIZATION_PENDING',
    GET_ORGANIZATION_FULFILLED: 'GET_ORGANIZATION_FULFILLED',
    GET_ORGANIZATION_REJECTED: 'GET_ORGANIZATION_REJECTED',


    SELECT_ORGANIZATION_NODE: 'SELECT_ORGANIZATION_NODE',

}

