export const PRODUCTS = {
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_PRODUCTS_PENDING: 'GET_PRODUCTS_PENDING',
    GET_PRODUCTS_FULFILLED: 'GET_PRODUCTS_FULFILLED',
    GET_PRODUCTS_REJECTED: 'GET_PRODUCTS_REJECTED',

    DEL_PRODUCT: 'DEL_PRODUCT',
    DEL_PRODUCT_PENDING: 'GET_PRODUCT_PENDING',
    DEL_PRODUCT_FULFILLED: 'GET_PRODUCT_FULFILLED',
    DEL_PRODUCT_REJECTED: 'GET_PRODUCT_REJECTED',


}

