export const PRODUCTS = {
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_PRODUCTS_PENDING: 'GET_PRODUCTS_PENDING',
    GET_PRODUCTS_FULFILLED: 'GET_PRODUCTS_FULFILLED',
    GET_PRODUCTS_REJECTED: 'GET_PRODUCTS_REJECTED',
}

