export const PRODUCTS = {

    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_PRODUCTS_PENDING: 'GET_PRODUCTS_PENDING',
    GET_PRODUCTS_FULFILLED: 'GET_PRODUCTS_FULFILLED',
    GET_PRODUCTS_REJECTED: 'GET_PRODUCTS_REJECTED',

    ADD_PRODUCT: 'ADD_PRODUCTS',
    ADD_PRODUCT_PENDING: 'ADD_PRODUCTS_PENDING',
    ADD_PRODUCT_FULFILLED: 'ADD_PRODUCTS_FULFILLED',
    ADD_PRODUCT_REJECTED: 'ADD_PRODUCT_REJECTED',

    UPDATE_PRODUCT: 'UPDATE_PRODUCTS',
    UPDATE_PRODUCT_PENDING: 'UPDATE_PRODUCTS_PENDING',
    UPDATE_PRODUCT_FULFILLED: 'UPDATE_PRODUCTS_FULFILLED',
    UPDATE_PRODUCT_REJECTED: 'UPDATE_PRODUCT_REJECTED',


    DEL_PRODUCT: 'DEL_PRODUCT',
    DEL_PRODUCT_PENDING: 'GET_PRODUCT_PENDING',
    DEL_PRODUCT_FULFILLED: 'GET_PRODUCT_FULFILLED',
    DEL_PRODUCT_REJECTED: 'GET_PRODUCT_REJECTED',


}

