export const GIT_USER = {
    GET_GIT_USER: 'GET_GIT_USER',
    GET_GIT_USER_PENDING: 'GET_GIT_USER_PENDING',
    GET_GIT_USER_FULFILLED: 'GET_GIT_USER_FULFILLED',
    GET_GIT_USER_REJECTED: 'GET_GIT_USER_REJECTED',

}

